import { Request } from "express";
import { genkit, z } from "genkit";
import awsBedrock from "genkitx-aws-bedrock";
import { TotoDelegate, UserContext } from "totoms";
import { getModel, SupportedModel } from "../util/Models";

/**
 * @example 
 * You can try this with the following Request Body: 
 * {
 *   "model": "anthropic.claude-3.7-sonnet", 
 *   "prompt": "So this is what I need basically. Sweet potatoes, proscutto, leua postai, riskicks, jam, musli noa, pasta, spaghetti, let malk, greek jogurt, meat, salt. I guess that's it. Yeah. ok. Also Caroline's bread. And eggs. done."
 * }
 */
export class TranscriptionGrounding extends TotoDelegate<GroundingRequest, GroundingResponse> {

    protected async do(req: GroundingRequest, userContext?: UserContext): Promise<GroundingResponse> {

        const ai = genkit({
            plugins: [
                awsBedrock({ region: "eu-north-1" }),
            ],
            model: getModel(req.model, "eu"),
        });

        const expectedOutputSchema = z.object({
            items: z.array(z.string().describe("Name of the item in the grocery shopping list")).describe("List of items in the shopping list")
        })

        const names = [
            "Eggs",
            "Letmælk",
            "Greek yogurt",
            "Bacon",
            "Havremælk",
            "Havremælk barista",
            "Bananas ",
            "Fruit",
            "Toilet paper",
            "N bread",
            "C bread",
            "Butter",
            "Cheese",
            "Grissini",
            "Tissues",
            "Baby wipes",
            "Bacon i tern",
            "Diapers",
            "Bread N",
            "Coffee",
            "Dentasticks",
            "Pasta ",
            "Mozzarella",
            "Parmesan",
            "Majskiks for Noah",
            "Peanut butter",
            "Bread c",
            "Foofies",
            "Dishwashing liquid",
            "Rice cakes",
            "Coffee c",
            "Rapskim Olie",
            "N musli",
            "Salad",
            "N yogurt",
            "Wasa",
            "Spaghetti ",
            "Almonds",
            "Tuna",
            "Nachos",
            "Chicken",
            "Griseøre",
            "Tomatoes",
            "Olives",
            "Coffee N",
            "Kitchen paper",
            "Medister",
            "Barista Havremælk",
            "Rugkiks ",
            "Avocado ",
            "Walnuts",
            "Olive oil ",
            "Dark chocolate",
            "Prosciutto cotto",
            "Crackers",
            "Frugt stang ",
            "Apricots ",
            "C musli",
            "N coffe",
            "Gouda",
            "Kidney beans",
            "Beans",
            "Rice",
            "Yoghurt ",
            "Marmelade",
            "Dishwashing tabs",
            "Tomato sauce",
            "Small biscos ",
            "Carrots",
            "Ostehaps ",
            "Meat",
            "Croutons",
            "Ristede løg",
            "Soup",
            "Flour 00",
            "Honey ",
            " Butter",
            "Veggie meat",
            "Fruit for N",
            "Peas",
            "Grapes",
            " Coffee C",
            "Jalapeños",
            "Broccoli",
            "Garlic",
            "Musli N",
            "Cucumber",
            "Syrup",
            "Havregryn",
            "Sugar",
            "Onions",
            "Sweet potato",
            "Hakket Okse",
            "Manitoba flour",
            "Syltede agirker ",
            "Dog shit bags",
            "Koldskål ",
            "Hakket Okse big pack",
            "Fruit ",
            "Tomato Sauce x2",
            "Tacos ",
            "Hazelnuts",
            "Dried apricots",
            "Flour",
            "Black beans",
            "Oranges ",
            "Black beans x2",
            "Musli Noah",
            "Cotton pads",
            "Persille",
            "Peperoni (red)",
            "Fruit for pancakes?",
            "Noah shower gel",
            "Kaki",
            "C coffee",
            "Maize flour",
            "Artichokes",
            "Olives ",
            "Lemon",
            "Chocolate",
            "Veggies",
            "Kål",
            "Bønner",
            "Beer",
            "Dishwashing brush ",
            "Dried apr ",
            "Brie",
            "Toilet paper x 2",
            "Bread crusts",
            "Selleri",
            "Musli ",
            "Salt ",
            "Kikærter",
            "Clementines",
            "Fire burners",
            "Dinner",
            "N choco coffe",
            "Dry Yeast",
            "Green peas",
            "Ricotta",
            "Syltede løg ",
            "Salmon",
            "Red meat",
            "Panna",
            "Bagepulver",
            "C coffee 10 & 6",
            "Something for Dinner ",
            "Universal rengøring",
            "Yogurt  Noah",
            "Oven paper ",
            "Fruit for us",
            "Sweet p ",
            "Smallest tub you can find of creme fraiche",
            "Dinner for noah ",
            "Coke",
            "Kalk tabs",
            "Kiwi",
            "Rugbrød n",
            "Juice",
            "Milk",
            "Cheese like brie or some ",
            "Apples or something ",
            "Grated cheese",
            "Risengrød",
            "Rosmarin",
            "Berrries",
            "Salt",
            "C coffee dark purple",
            "Lime",
            "Tipo 00",
            "Lasagne ",
            "Any other snack ideas for Noah ",
            "Red wine",
            "Snacks",
            "Everything for nachos",
            "Stuff for nachos (not avocado)",
            "Noah Musli",
            "Peanuts ",
            "Caro coffee",
            "Falafel",
            "Blueberries",
            "One lime",
            "Grapes?",
            "Swim diapers ",
            "Sun lotion 20",
            "N butter",
            "Entrecote",
            "Stuff for smørrebrød",
            "Frozen peas",
            "Olive oil",
            "Koriander",
            "Eggs ",
            "Diapers ",
            "Pear",
            "Fruit for pancakes",
            "Battery for temp. sensor",
            "Bread C",
            "Soy sauce",
            "Kammerjunkere ",
            "Food containers",
            "Pebernødder",
            "Toast bread",
            "Sødmælk",
            "Noci",
            "Just everything we used to have in the fridge i guess 😅",
            "Apples",
            "Grapes ",
            "Sød mælk",
            "Baby shampoo ",
            "Treo",
            "Cashews",
            "Spidskommen",
            "Noah toothbrush if you have time",
            "Pizza ",
            "Fruit, apples, grapes",
            "Vatrondeller",
            "Farina",
            "Buttee",
            "Fuldkorn wraps",
            "Sesam olie",
            "Coke ",
            "Easter chocolate",
            "Zucchini",
            "Eggs and bacon just cause we can always use more",
            "Røget Laks",
            "Chips for nachos (2)",
            "Stuff for pancskes ",
            "Gouda x2",
            "Shaving cream",
            "Small tomatoes",
            "Basilikum",
            "Batteries",
            "Butter C",
            "Burger bread",
            "Bagepapir",
            "Loki food ",
            "Pepper",
            "Syrup ",
            "C coffee caramel",
            "Head & Shoulders",
            "Pesto",
            "Raisins, maybe Noah wants to try",
            "Coffee c, number 13, 8 and caramel",
            "Fennel",
            "Rugbrød c",
            "Hands Lotion",
            "White wine",
            "Æbleskive",
            "Caro musli ",
            "Crackers",
            "Timian",
            "Dog biscos",
            "Sun Lotion",
            "Svampe",
            "Noah water bottle ",
            "Kefir",
            "Baking soda",
            "Trash bags ",
            "AAA batteries ",
            "Celery",
            "Smoked salmon",
            "Some other veggie for the wraps, Can’t think of anything",
            "Jam",
            "Strawberries",
            "Water bottles for supply ",
            "Bread ",
            "Cheese packs x2",
            "Bacon ",
            "Shampoo N",
            "Coffe",
            "Verza",
            "Wrapping paper",
            "Big hand soap ",
            "Chips",
            "Watermelon or something",
            "Pig meat",
            "Asparagus",
            "Bread",
            "Loki ball",
            "Leverpostej",
            "Opvaskemiddel"
        ]

        const response = await ai.generate({
            system: `
                You are a supermarket experts that knows all typical items that can be found in a supermarket in Denmark and Italy. 
                You know ALL the names of grocery items in English (main language), Danish and Italian (second languages). 
                You will receive lists of supermarket items (groceries shopping list) made by a user. 
                The list is made from a AI-generated transcript of an audio recording where the user recorded items to be bought at the supermarket. 

                Important: the transcript will MOST LIKELY contain errors as the user uses multiple languages, with the majority of items being dictated in English, but some in Danish and Italian. 
                The AI that transcribes the audio is english-speaking so Danish (mostly) and Italian (some) items will most likely be mispelled and look like gibberish to you. 

                Your task is to create the groceries shopping list from the transcript and CORRECT all the mispelled or misinterpreted item names. 

                These are the most common items picked by the user: ${JSON.stringify(names)}.
                Use this list to try to reconcile names whenever you have a doubt. 
            `,
            prompt: `
                Create the groceries shopping list from the following transcription of the user's desires of items to be added to the list: 
                ${req.prompt} 
            `,
            // output: { schema: expectedOutputSchema } 
        });

        const secondIteration = await ai.generate({
            prompt: `Convert this into a structured array: ${response.text}`,
            output: { schema: expectedOutputSchema }
        })

        return { response: secondIteration.output, usage: response.usage, fullResponse: response, text: response.text, a: response.data, b: response.messages };
    }

    parseRequest(req: Request): GroundingRequest {
        return {
            model: req.body.model || "amazon.nova-pro",
            prompt: req.body.prompt
        }
    }

}

interface GroundingRequest {
    model: SupportedModel;
    prompt: string;
}
interface GroundingResponse { }